// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

#nullable disable

namespace SmartSchool.WebAPI.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20221230200652_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Information Systems"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Computer Science"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrerequisiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Workload")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PrerequisiteId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Name = "Math",
                            TeacherId = 1,
                            Workload = 0
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3,
                            Name = "Math",
                            TeacherId = 1,
                            Workload = 0
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Name = "Physics",
                            TeacherId = 2,
                            Workload = 0
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Name = "Portuguese",
                            TeacherId = 3,
                            Workload = 0
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Name = "English",
                            TeacherId = 4,
                            Workload = 0
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            Name = "English",
                            TeacherId = 4,
                            Workload = 0
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            Name = "English",
                            TeacherId = 4,
                            Workload = 0
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 1,
                            Name = "Programing",
                            TeacherId = 5,
                            Workload = 0
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 2,
                            Name = "Programing",
                            TeacherId = 5,
                            Workload = 0
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 3,
                            Name = "Programing",
                            TeacherId = 5,
                            Workload = 0
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Registration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            BirthDate = new DateTime(2005, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marta",
                            Registration = 1,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6208),
                            Surname = "Kent",
                            Telephone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            BirthDate = new DateTime(2005, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paula",
                            Registration = 2,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6216),
                            Surname = "Isabela",
                            Telephone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            BirthDate = new DateTime(2005, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laura",
                            Registration = 3,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6220),
                            Surname = "Antonia",
                            Telephone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            BirthDate = new DateTime(2005, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luiza",
                            Registration = 4,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6223),
                            Surname = "Maria",
                            Telephone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            BirthDate = new DateTime(2005, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lucas",
                            Registration = 5,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6227),
                            Surname = "Machado",
                            Telephone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            BirthDate = new DateTime(2005, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pedro",
                            Registration = 6,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6232),
                            Surname = "Alvares",
                            Telephone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            BirthDate = new DateTime(2005, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Paulo",
                            Registration = 7,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6236),
                            Surname = "José",
                            Telephone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Note")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentsCourses");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.StudentDiscipline", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Note")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId", "DisciplineId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("StudentsDisciplines");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 2,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6256)
                        },
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 4,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6296)
                        },
                        new
                        {
                            StudentId = 1,
                            DisciplineId = 5,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6297)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 1,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6298)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 2,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6299)
                        },
                        new
                        {
                            StudentId = 2,
                            DisciplineId = 5,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6301)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 1,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6301)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 2,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6302)
                        },
                        new
                        {
                            StudentId = 3,
                            DisciplineId = 3,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6303)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 1,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6304)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 4,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6305)
                        },
                        new
                        {
                            StudentId = 4,
                            DisciplineId = 5,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6306)
                        },
                        new
                        {
                            StudentId = 5,
                            DisciplineId = 4,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6307)
                        },
                        new
                        {
                            StudentId = 5,
                            DisciplineId = 5,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6307)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 1,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6308)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 2,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6309)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 3,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6309)
                        },
                        new
                        {
                            StudentId = 6,
                            DisciplineId = 4,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6311)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 1,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6312)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 2,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6313)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 3,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6314)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 4,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6315)
                        },
                        new
                        {
                            StudentId = 7,
                            DisciplineId = 5,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6315)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Record")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Name = "Lauro",
                            Record = 1,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6015),
                            Surname = "Oliveira",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Name = "Roberto",
                            Record = 2,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6027),
                            Surname = "Soares",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Name = "Ronaldo",
                            Record = 3,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6028),
                            Surname = "Marconi",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Name = "Rodrigo",
                            Record = 4,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6029),
                            Surname = "Carvalho",
                            Telephone = ""
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Name = "Alexandre",
                            Record = 5,
                            StartDate = new DateTime(2022, 12, 30, 17, 6, 52, 161, DateTimeKind.Local).AddTicks(6030),
                            Surname = "Montanha",
                            Telephone = ""
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Discipline", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Course", "Course")
                        .WithMany("Disciplines")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Discipline", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteId");

                    b.HasOne("SmartSchool.WebAPI.Models.Teacher", "Teacher")
                        .WithMany("Disciplines")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Prerequisite");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.StudentCourse", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.StudentDiscipline", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Discipline", "Discipline")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Student", "Student")
                        .WithMany("StudentsDisciplines")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Course", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Discipline", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Student", b =>
                {
                    b.Navigation("StudentsDisciplines");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Teacher", b =>
                {
                    b.Navigation("Disciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
